### ISSUE TITLE
Next iteration of ronin

### ISSUE THREAD

**Issue by daviddias** [vadimdemedes/ronin#37]
Hi @vdemedes! How have you been?

I've been using ronin for a while and I'm really enthusiast of the features it offers, recommending it to anyone that wants to do a CLI in Node.js. However, the project has been stale for a while and the lack of new features, specially when it comes to be more descriptive about documentation of the commands, start making ronin missing some of our goals.

I'm aware that you are super busy, but if you could kick off the next iteration and lay out the vision, me, @richardlitt and other folks would be happy to help you get there :)

**Comment by vdemedes** [comment]
Hey guys, let me get back to you tomorrow ;)

**Comment by vdemedes** [comment]
Hey @diasdavid and @richardlitt, I know it's been long overdue and I'm sorry for this, it's been a lot of stuff on my plate lately.

So, the next iteration of Ronin. Currently, it's a pile of unflexible code, but with a nice list of features and ideas. I was thinking how to make the underlying code easy and straightforward, as well as simple to customize and introduce new features.

I decided to go Express/Connect route. What this means is, now we have 2 separate projects:

- Sushi (like Connect) - a middleware layer for CLI apps.
- Ronin (like Express) - a project that uses Sushi underneath and bundles a lot of helpful middleware.

Ronin will keep a list of its existing features, like auto-registration of commands. However, it'll remain clean, because it will basically be a bundle of individual middleware for Sushi.

As for Sushi, it's simply a middleware layer, without any fancy functionality. Think of it like Connect for CLI apps, instead of HTTP servers. Today I pushed a rewritten version of Sushi, as well as example help middleware:

- sushi - https://github.com/vdemedes/sushi
- sushi-help - https://github.com/vdemedes/sushi-help

Would love to hear your feedback, ideas and suggestions! What use cases did Ronin not fulfill in your projects? What was unneeded? What features you liked (so that I know what to keep in the next major iteration of Ronin)?

Thank you a lot of understanding and your patience!
